server:
  port: ${PORT}

spring:
  application:
    name: word-online-matching
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: never

#logging:
#  level:
#    org.springframework:
#      DEBUG

team6515:
  server:
    account:
      url: ${ACCOUNT_SERVER_URL}
    game:
      url: ${GAME_SERVER_URL}


jwt:
  access-private-key: ${JWT_PRIVATE_KEY}
  access-public-key: ${JWT_PUBLIC_KEY}